# Site settings
title: Mass WebDev
email: hello@massweb.dev
description: > # this means to ignore newlines until "baseurl:"
baseurl: "massweb.dev/" # the subpath of your site, e.g. /blog/
url: "https://www.massweb.dev/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
